name: "Dis-Orientation Collective"
description: "All the things you ought to know about universities"

url: "http://dis-orientation.info/"

paginate: 10

markdown: kramdown
permalink: pretty
pygments: true